executors:
  circleci-go:
    docker:
      - image: cimg/go:1.16-browsers
    working_directory: /home/circleci/go/src/palantir/godel-okgo-asset-importalias

homepath: &homepath
  homepath: /home/circleci

gopath: &gopath
  gopath: /home/circleci/go

version: 2.1

orbs:
  go: palantir/go@0.0.23
  godel: palantir/godel@dev:develop-9cc21466bd27e99a964a353f10e610113e4fb84e

all-tags-filter: &all-tags-filter
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  verify-test-dist-publish:
    jobs:
      - godel/verify:
          name: verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          <<: *all-tags-filter
      - godel/test:
          name: test
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          <<: *all-tags-filter
      - godel/dist:
          name: dist
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          <<: *all-tags-filter
